package section2;

import java.awt.Color;
import org.jointheleague.graphical.robot.Robot;

public class MyFirstJavaProgram {
	
	public static void main(String[] args) {
		
		// START HERE
		Robot Bob = new Robot("batman");
		Bob.setSpeed(23);
		Bob.penDown();
		Bob.setRandomPenColor();
		Bob.turn(90);
		Bob.move(90);
		Bob.setRandomPenColor();
		Bob.turn(90);
		Bob.move(90);
		Bob.setRandomPenColor();
		Bob.turn(90);
		Bob.move(90);
		Bob.setRandomPenColor();
		Bob.turn(90);
		Bob.move(90);
		Bob.setRandomPenColor();
		Bob.setRandomPenColor();
		Bob.turn(90);
		Bob.move(90);
		Bob.setRandomPenColor();
		Bob.turn(90);
		Bob.move(90);
		Bob.setRandomPenColor();
		Bob.turn(90);
		Bob.move(90);
		Bob.setRandomPenColor();
		Bob.turn(90);
		Bob.move(90);
		Bob.setRandomPenColor();
		Bob.setRandomPenColor();
		Bob.turn(90);
		Bob.move(90);
		Bob.setRandomPenColor();
		Bob.turn(90);
		Bob.move(90);
		Bob.setRandomPenColor();
		Bob.turn(90);
		Bob.move(90);
		Bob.setRandomPenColor();
		Bob.turn(90);
		Bob.move(90);
		Bob.setRandomPenColor();
		Bob.setRandomPenColor();
		Bob.turn(90);
		Bob.move(90);
		Bob.setRandomPenColor();
		Bob.turn(90);
		Bob.move(90);
		Bob.setRandomPenColor();
		Bob.turn(90);
		Bob.move(90);
		Bob.setRandomPenColor();
		Bob.turn(90);
		Bob.move(90);
		Bob.setRandomPenColor();
		Bob.setRandomPenColor();
		Bob.turn(90);
		Bob.move(90);
		Bob.setRandomPenColor();
		Bob.turn(90);
		Bob.move(90);
		Bob.setRandomPenColor();
		Bob.turn(90);
		Bob.move(90);
		Bob.setRandomPenColor();
		Bob.turn(90);
		Bob.move(90);
		Bob.setRandomPenColor();
		Bob.setRandomPenColor();
		Bob.turn(90);
		Bob.move(90);
		Bob.setRandomPenColor();
		Bob.turn(90);
		Bob.move(90);
		Bob.setRandomPenColor();
		Bob.turn(90);
		Bob.move(90);
		Bob.setRandomPenColor();
		Bob.turn(90);
		Bob.move(90);
		Bob.setRandomPenColor();
		Bob.setRandomPenColor();
		Bob.turn(90);
		Bob.move(90);
		Bob.setRandomPenColor();
		Bob.turn(90);
		Bob.move(90);
		Bob.setRandomPenColor();
		Bob.turn(90);
		Bob.move(90);
		Bob.setRandomPenColor();
		Bob.turn(90);
		Bob.move(90);
		Bob.setRandomPenColor();
		Bob.setRandomPenColor();
		Bob.turn(90);
		Bob.move(90);
		Bob.setRandomPenColor();
		Bob.turn(90);
		Bob.move(90);
		Bob.setRandomPenColor();
		Bob.turn(90);
		Bob.move(90);
		Bob.setRandomPenColor();
		Bob.turn(90);
		Bob.move(90);
		Bob.setRandomPenColor();
		Bob.setRandomPenColor();
		Bob.turn(90);
		Bob.move(90);
		Bob.setRandomPenColor();
		Bob.turn(90);
		Bob.move(90);
		Bob.setRandomPenColor();
		Bob.turn(90);
		Bob.move(90);
		Bob.setRandomPenColor();
		Bob.turn(90);
		Bob.move(90);
		Bob.setRandomPenColor();
		Bob.setRandomPenColor();
		Bob.turn(90);
		Bob.move(90);
		Bob.setRandomPenColor();
		Bob.turn(90);
		Bob.move(90);
		Bob.setRandomPenColor();
		Bob.turn(90);
		Bob.move(90);
		Bob.setRandomPenColor();
		Bob.turn(90);
		Bob.move(90);
		Bob.setRandomPenColor();
	
		
		
	}
}
